# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class EnterGameReq(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEnterGameReq(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnterGameReq()
        x.Init(buf, n + offset)
        return x

    # EnterGameReq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnterGameReq
    def Platform(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # EnterGameReq
    def Account(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # EnterGameReq
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def EnterGameReqStart(builder): builder.StartObject(3)
def EnterGameReqAddPlatform(builder, platform): builder.PrependUint16Slot(0, platform, 0)
def EnterGameReqAddAccount(builder, account): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(account), 0)
def EnterGameReqAddVersion(builder, version): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(version), 0)
def EnterGameReqEnd(builder): return builder.EndObject()
