# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class HeartBeatResp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHeartBeatResp(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeartBeatResp()
        x.Init(buf, n + offset)
        return x

    # HeartBeatResp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeartBeatResp
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HeartBeatRespStart(builder): builder.StartObject(1)
def HeartBeatRespAddTimestamp(builder, timestamp): builder.PrependUint32Slot(0, timestamp, 0)
def HeartBeatRespEnd(builder): return builder.EndObject()
