# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class LoginReq(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLoginReq(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LoginReq()
        x.Init(buf, n + offset)
        return x

    # LoginReq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LoginReq
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # LoginReq
    def Password(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def LoginReqStart(builder): builder.StartObject(2)
def LoginReqAddUsername(builder, username): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)
def LoginReqAddPassword(builder, password): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(password), 0)
def LoginReqEnd(builder): return builder.EndObject()
