# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class ProtoID(object):
    EnterGame = 1
    EnterGameResp = 2
    HeartBeatReq = 3
    HeartBeatResp = 4
    Max = 5

